config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'movies#index'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  resources :movies do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def redirect_if_not_signed_in
    redirect_to root_path if !user_signed_in?
  end
  
  def redirect_if_signed_in
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_movie, only: [:show,:edit,:update,:destroy]
    before_action :redirect_if_not_signed_in, only: [:new]
    def index
      @movies = Movie.all
    end

    def show
        @movie
    end

    def create
        @movie = Movie.create(create_movie)
        if @movie.save 
            redirect_to movie_path(@movie) 
        else
            redirect_to root_path
        end
    end
    
    def update
        p update_movie
       @movie.update(update_movie)
        redirect_to root_path
       
    end
    def edit
        @movie
    end
    def delete
        @movie
    end
    def destroy
        @movie.destroy!
        redirect_to root_path
    end
    def new
        @movie = Movie.new
    end
    private

    def set_movie
        p params
        @movie = Movie.find(params[:id])
    end

    def update_movie
        params.require(:movie).permit(:name, :producer, :country, :synopsis)
        .merge(user_id: current_user.id)
    end
    def create_movie
        params.require(:movie).permit(:name, :producer, :country, :synopsis)
        .merge(user_id: current_user.id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit( :name, 
                                    :email, 
                                    :password, 
                                    :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit( :name, 
                                    :email, 
                                    :password, 
                                    :password_confirmation, 
                                    :current_password)
    end
  end

app/helpers/application_helper.rb
require 'navigation_helper.rb'
include MoviesHelper
module ApplicationHelper
  include NavigationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
    def create_new_movie_partial_path
        if user_signed_in?
          'movies/new'
        else
          'movies/branch/create_new_movie/not_signed_in'
        end
      end
      def no_movies_partial_path
        @movies.empty? ? 'movies/branch/no_movies' : 'shared/empty_partial'
      end
      def movie_format_partial_path
        current_page?(root_path) ? 'movies/movie/home_page' : 'movies/movie/branch_page'
      end

    
end

app/helpers/navigation_helper.rb
module NavigationHelper

    def collapsible_links_partial_path
      if user_signed_in?
        'layouts/navigation/collapsible_elements/signed_in_links'
      else
        'layouts/navigation/collapsible_elements/non_signed_in_links'
      end
    end
    
  end

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
<%= link_to 'Blockbuster', root_path, class: 'navbar-brand' %>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
      <li ><%= link_to 'Login', login_path %></li>
      <li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
      <li class="dropdown pc-menu">
        <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span id="user-name"><%= current_user.name %></span>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>

      <li class="mobile-menu">
        <%= link_to 'Edit Profile', edit_user_registration_path %>
      </li>
      <li class="mobile-menu">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      </li>

app/views/movies/_branch.html.erb
<div id="branch-main-content" class="container">
  <div class="row">
    <h1 class="page-title"><%= page_title %></h1>
    <%= render 'movies/branch/create_new_movie', branch: branch %>
  </div><!-- row -->
<div class="row">
  <%= render  'posts/branch/search_form', 
              branch: branch,
              search_placeholder: search_placeholder %>
</div><!-- row -->


  <div class="row">
    <div class="col-sm-12" id="feed">
      <%= render @movies %>
      <%= render no_movies_partial_path %>		
    </div>
  </div><!-- row -->	

  <div class="infinite-scroll">
    <%= will_paginate @movies %>
  </div>
</div><!-- container -->

app/views/movies/_modal.html.erb
<!-- Modal -->
<div  class="myModal" 
      tabindex="-1"
      style="display: none;" 
      id="info_modal"
      role="dialog" 
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h1 id="movie_name" class="modal-name"></h1>
        <button type="button" 
                class="close" 
                data-dismiss="modal" 
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <div class="loaded-data">
            <h3 class="modal-synopsis"></h3>
            <p class="modal-producer"></p>
            
            <p class="modal-country"></p>
          </div><!-- loaded-data -->
        </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="col-sm-3 single-post-card" id=<%= movie_path(movie.id) %>>
  <div class="card">
    <div class="card-block">
      <h4 class="posted-name post-text">
        <%= truncate(movie.name, :length => 60) %>
      </h4>
      <div class="post-content">
       
        <div class="posted-producer">Producer: <%= movie.producer %></div>
        <div class="posted-country">Country: <%= movie.country %></div>
        <div class="posted-synopsis"><%= movie.synopsis %></div>
        <div class="">Posted by <%= movie.user.name %></div>
      </div>
    </div>
    <div class="col-sm-4">
      <%= link_to "Edit", controller: "movies", action: "edit", :id => movie.id %>
      <%= link_to 'Destroy', '#', "data-toggle"=>"modal", "data-target" => "#delete-#{movie.id}" %>

    </div>
      <div class="modal fade" id="delete-<%= movie.id %>" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">Confirmation Box</button>
          </div>
          <div class="modal-body">
            <p>¿Are you sure to delete this movie?</p>
          </div>
          <div class="modal-footer">
            <div class="modal-footer">
              <%= link_to 'Delete', movie_path(movie), method: :delete, "data-toggle"=>"modal", :class => 'btn btn-danger' %>
                <a href="#" data-dismiss="modal" class="btn btn-warning">Cancel</a>
            </div>
          </div>
        </div>
      </div>
   </div>
  </div><!-- card -->
</div><!-- col-sm-3 -->

app/views/movies/branch/_create_new_movie.html.erb
<div class="col-sm-12">
  <div class="col-sm-8 col-sm-offset-2">
    <%= render create_new_movie_partial_path, branch: branch %>
  </div><!-- col-sm-8 -->	
</div><!-- col-sm-12 -->

app/views/movies/branch/_no_movies.html.erb
<div class="text-center">Currently there are no published movies</div>

app/views/movies/branch/_search_form.html.erb
<div class="col-sm-12">
  <%= form_tag(send("#{branch}_movies_path"), 
               :method => "get", 
               id: "search-form") do %>
    <i class="fa fa-search" aria-hidden="true"></i>
    <%= text_field_tag  :search, 
                        params[:search], 
                        placeholder: search_placeholder, 
                        class: "form-control" %>
  <% end %>
</div><!-- col-sm-12 -->

app/views/movies/branch/create_new_movie/_not_signed_in.html.erb
<div class="text-center login-branch">
  To create a new movie you have to 
  <%= link_to 'Login', 
              login_path, 
              class: 'login-button login-button-branch' %>
</div>

app/views/movies/branch/create_new_movie/_signed_in.html.erb
<div class="new-post-button-parent">
  <span>Cannot find anyone? Try to: </span>
  <%= link_to "Create a new movie", 
              create_new_movie_partial_path(branch: branch), 
              :class => "new-post-button" %>
</div>

app/views/movies/edit.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a movie post</h1>
        <%= render 'movies/edit/movie_form' %>
    </div>
  </div>
</div>

app/views/movies/edit/_movie_form.html.erb
<%= bootstrap_form_for(@movie) do |f| %>
  <%= f.text_field  :name, 
                    maxlength: 100, 
                    placeholder: 'Name', 
                    class: 'form-control',
                    required: true, 
                    minlength: 2
                   %>
  <%= f.text_area :synopsis, 
                  rows: 6,
                  required: true, 
                  minlength: 20,
                  maxlength: 1000,
                  placeholder: 'Describe movie content.', 
                  class: 'form-control' %>
    <%= f.text_field  :country, 
                    maxlength: 100, 
                    placeholder: 'Country origin', 
                    class: 'form-control',
                    required: true, 
                    minlength: 2
                  %>
    <%= f.text_field  :producer, 
                    maxlength: 100, 
                    placeholder: 'Producer\'s name', 
                    class: 'form-control',
                    required: true, 
                    minlength: 5
                    %>                    
  <%= f.submit "Update", class: 'form-control' %>
<% end %>

app/views/movies/index.html.erb
<%= render 'movies/modal' %>

<div class="container">
  <div class="row">
    <%= render 'movies/index/side_menu' %>
    <%= render 'movies/index/main_content' %>
  </div><!-- row -->
</div><!-- container -->

app/views/movies/index/_main_content.html.erb
<div id="main-content" class="col-sm-9">
  <%= render @movies %>
</div><!-- main-content -->

app/views/movies/index/_side_menu.html.erb
<div id="side-menu"  class="col-sm-3">
  <ul id="links-list">
    <%= link_to "Create new movie", controller: "movies", action: "new" %>
  </ul>
</div><!-- side-menu -->

app/views/movies/index/side_,menu/_no_login_required_links.html.erb
<li id="hobby">
  <%= link_to hobby_movies_path do %>
    <i class="fa fa-user-circle-o" aria-hidden="true"></i> Find a hobby buddy
  <% end %>
</li>

<li id="study">
  <%= link_to study_movies_path do %>
    <i class="fa fa-graduation-cap" aria-hidden="true"></i> Find a study buddy
  <% end %>
</li>

<li id="team">
  <%= link_to team_movies_path do %>
    <i class="fa fa-users" aria-hidden="true"></i> Find a team member
  <% end %>
</li>

app/views/movies/movie/_branch_page.html.erb
<div class="single-post-list" id=<%= movie_path(movie.id) %>>
  <%= truncate(movie.name, :length => 60) %>
  <div class="post-content">
    <div class="posted-by">Posted by <%= movie.user.name %></div>
    <h3><%= movie.name %></h3> 
    <p><%= movie.synopsis %></p>
    <%= link_to "I'm interested", movie_path(movie.id), class: 'interested' %> 
  </div>
</div>

app/views/movies/movie/_home_page.html.erb
<%= render movie_format_partial_path, movie: movie %>

app/views/movies/new.html.erb
<div class="container new-post">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Create a movie post</h1>
        <%= render 'movies/new/movie_form' %>
    </div>
  </div>
</div>

app/views/movies/new/_movie_form.html.erb
<%= bootstrap_form_for(@movie) do |f| %>
  <%= f.text_field  :name, 
                    maxlength: 100, 
                    placeholder: 'Name', 
                    class: 'form-control',
                    required: true, 
                    minlength: 2
                   %>
  <%= f.text_area :synopsis, 
                  rows: 6,
                  required: true, 
                  minlength: 20,
                  maxlength: 1000,
                  placeholder: 'Describe movie content.', 
                  class: 'form-control' %>
    <%= f.text_field  :country, 
                    maxlength: 100, 
                    placeholder: 'Country origin', 
                    class: 'form-control',
                    required: true, 
                    minlength: 2
                  %>
    <%= f.text_field  :producer, 
                    maxlength: 100, 
                    placeholder: 'Producer\'s name', 
                    class: 'form-control',
                    required: true, 
                    minlength: 5
                    %>                    
  <%= f.submit "Create a movie", class: 'form-control' %>
<% end %>

app/views/movies/show.html.erb
<div id="single-post-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Posted by <%= @movie.user.name %></div>
      <h3><%= @movie.name %></h3>
      <p><%= @movie.synopsis %></p>
    </div>
  </div><!-- row -->
</div>